In [ ]:
By now we already have a discussion on hypothesis testing  and z-test

In [ ]:
Inn statistical tests mein normal distribution k ek cousin ka bht use hota h
jisko hm bolte h t-distribution.

T-distribution is very much similar like z-test except the shape of t-distribution is highly
influenced by the sample size.
sample size ki waja h s t-distribution unfluence hoota h mtlb hill-dull sakta h.

with the very large sample size (n>120) we can safely conclude that t distribution is highly 
equal to normal distribution.


for small sample size (n<30) the shape of t-distribution becomes flatter in the middle and higher on the tails.

In [ ]:
sample : Let us say that the average indian man watches netflix for 60 min in a week.
    n = 144 , avg_time = 65 min , std dev = 10 min

In [ ]:
ques. what is the probability of getting a random sample of this size with a aforementiones stats by chance?

avg_ time of all indians = 60 min
one sample of size of 144 people ==== 65 min

what are the chances ki aapne populatiom m s ek din ek sample nikala and wo sample upr wale sample jaisa hee ho?

In [ ]:
t = 65-60/10/144**1/2 = 6.02
Ab t distribution table rea karege , aapko us table "infinite" d0f waali row m 6.02 ke sabse kareeb wali
value dhundni hogi

sabse karreeb value is 2.5 at 0.005 significance level.

The answer is 0.005 which is p-value in some sense.

mtlb aisa sample milne k chances bht km h.


In [1]:
10/12

0.8333333333333334

In [2]:
5/0.83

6.024096385542169

In [ ]:
Chi-square Test: 
1. It only categorical data (data in categories, gender,color) , but not numerical or continouus data
  like height or weight.

2. The sample size must be good enough.
eg: There are two hypotheses:
        1. gender and preference for cats or dogs are independent .
        2. gender and preference for cats or dogs are not independent.
        




In [3]:
#for women and cat
473 * 438

207174

In [4]:
207174/962


215.35758835758836

In [5]:
#for men and dog 
a = 489 * 524

In [6]:
a/962

266.3575883575884

In [7]:
b = 473 * 524

In [8]:
b/962

257.6424116424116

In [ ]:
Scipy --- scientific Python.
It is used to perform high-level mathematics and inferential statistics on datasets.
Both numpy and scipy works hand in hand and it is assumed that scipy works above numpy

In [1]:
import numpy as np
import scipy 

In [ ]:
-- It is used to calculate integration, Fourier Transformation , Interpolation and inferential statistics.

In [2]:
import scipy.stats as stats

In [4]:
stats.chi2.ppf(0.99,6) #It is just an example aako 1 m s 21.11 minums krna h 
#and dof 19 hee leni h.

16.811893829770927

In [5]:
import seaborn as sns
import pandas as pd

In [6]:
dataset = sns.load_dataset("tips")

In [7]:
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
h0: smoker and gender are independent
h1 : smoker and gender is dependent

In [8]:
dataset_table = pd.crosstab(dataset["sex"],dataset["smoker"])

In [9]:
dataset_table

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [10]:
dataset_table.values

array([[60, 97],
       [33, 54]], dtype=int64)

In [15]:
observed_values = dataset_table.values

In [16]:
observed_values

array([[60, 97],
       [33, 54]], dtype=int64)

In [11]:
val = stats.chi2_contingency(dataset_table)

In [12]:
val

(0.008763290531773594, 0.925417020494423, 1, array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [ ]:
0.008763 ------ test-statistics value
0.9254 ------ p-value
1 ---- d.o.f
array --- array of expected values

In [13]:
expected_values = val[3]

In [14]:
expected_values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [17]:
from scipy.stats import chi2
chi_square = sum([(o-e)**2/e for o,e in zip(observed_values, expected_values)])
chi_square_statistic = chi_square[0] + chi_square[1]

In [18]:
print("chi_square_statistic = " , chi_square_statistic)

chi_square_statistic =  0.001934818536627623


In [19]:
p_value = 1- chi2.cdf(x = chi_square_statistic , df = 1)

In [20]:
p_value

0.964915107315732

In [21]:
if p_value<=0.05:
    print("Reject Ho , There is a relationship between smoker and gender")
else:
    print("There is no relationship between smoker and gender")

There is no relationship between smoker and gender


In [ ]:
T-Test : It is used to calculate either there is a specific difference in between the mean of certain features.

In [22]:
ages = [10,12,2,3,45,12,45,23,14,76,67,89,98,54,32,30,21,22,23,24,34,35,36,61,41,42,43,44,44,56,17,18,19]

In [23]:
len(ages)

33

In [24]:
np.mean(ages)

36.121212121212125

In [25]:
#Lets take some sample
sample_size = 10
age_sample = np.random.choice(ages,10)

In [26]:
age_sample

array([61, 44, 56, 56, 12, 12, 76, 10, 54, 45])

In [ ]:
H0: My population mean is equal to sample mean.
H1 :Population mean is not equal to sample  Mean

In [27]:
from scipy.stats import ttest_1samp

In [28]:
ttest,p_value = ttest_1samp(age_sample,36.12)

In [29]:
ttest

0.8794309644412548

In [30]:
p_value

0.4020380522708664

In [31]:
if p_value<=0.05:
    print("We are rejecting the null hypothesis")
else:
    print("We are fail to reject null hypothesis")

We are fail to reject null hypothesis


In [ ]:
data Analyst : There focus is to find an insight from the dataset.
pandas , sklearn , numpy , scipy --- Advance pandas
" Wes Mckinney" --- developer of pandas library