In [ ]:
OpenCV is used for image - preprocessing , object-detection etc..
It was started at intel in 1999 by gary bradskey and release in the year 2000.
CV ---- computer Vision
opencv python is the opencv api for python programming language.

In [ ]:
You need to install it --
conda install - c conda forge opencv
pip install opencv-python==3.7(python version)

In [1]:
import cv2

In [2]:
img = cv2.imread("cat.jpg")

In [3]:
img

array([[[ 20,  20,  20],
        [ 20,  20,  20],
        [ 19,  19,  19],
        ...,
        [ 54,  65,  73],
        [ 55,  64,  73],
        [ 55,  64,  73]],

       [[ 20,  20,  20],
        [ 20,  20,  20],
        [ 19,  19,  19],
        ...,
        [ 54,  65,  73],
        [ 55,  64,  73],
        [ 55,  64,  73]],

       [[ 20,  20,  20],
        [ 20,  20,  20],
        [ 19,  19,  19],
        ...,
        [ 54,  65,  73],
        [ 55,  64,  73],
        [ 55,  64,  73]],

       ...,

       [[165, 160, 169],
        [172, 167, 176],
        [181, 176, 185],
        ...,
        [200, 192, 199],
        [200, 192, 199],
        [200, 192, 199]],

       [[167, 162, 171],
        [175, 170, 179],
        [183, 178, 187],
        ...,
        [201, 193, 200],
        [201, 193, 200],
        [201, 193, 200]],

       [[168, 163, 172],
        [176, 171, 180],
        [184, 179, 188],
        ...,
        [202, 194, 201],
        [202, 194, 201],
        [202, 194, 201]]

In [4]:
img.shape

(720, 1280, 3)

In [7]:
cv2.imshow("image" , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
cv2.line(img,(0,0),(300,300),(147,96,44),10)

array([[[147,  96,  44],
        [147,  96,  44],
        [147,  96,  44],
        ...,
        [ 54,  65,  73],
        [ 55,  64,  73],
        [ 55,  64,  73]],

       [[147,  96,  44],
        [147,  96,  44],
        [147,  96,  44],
        ...,
        [ 54,  65,  73],
        [ 55,  64,  73],
        [ 55,  64,  73]],

       [[147,  96,  44],
        [147,  96,  44],
        [147,  96,  44],
        ...,
        [ 54,  65,  73],
        [ 55,  64,  73],
        [ 55,  64,  73]],

       ...,

       [[165, 160, 169],
        [172, 167, 176],
        [181, 176, 185],
        ...,
        [200, 192, 199],
        [200, 192, 199],
        [200, 192, 199]],

       [[167, 162, 171],
        [175, 170, 179],
        [183, 178, 187],
        ...,
        [201, 193, 200],
        [201, 193, 200],
        [201, 193, 200]],

       [[168, 163, 172],
        [176, 171, 180],
        [184, 179, 188],
        ...,
        [202, 194, 201],
        [202, 194, 201],
        [202, 194, 201]]

In [9]:
cv2.imshow("image" , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
font = cv2.FONT_ITALIC

In [12]:
img = cv2.putText(img,"OPEN-CV",(300,500),font,4,(0,255,255),10)

In [13]:
cv2.imshow("image" , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [14]:
#To crop a image
cropped_image = img[100:500,250:700]

In [15]:
cv2.imshow("image" , cropped_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [16]:
resized_image = cv2.resize(img,(300,300))

In [17]:
cv2.imshow("image" , resized_image)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [18]:
cv2.circle(img,(110,220),105,(0,255,0),-1)

array([[[147,  96,  44],
        [147,  96,  44],
        [147,  96,  44],
        ...,
        [ 54,  65,  73],
        [ 55,  64,  73],
        [ 55,  64,  73]],

       [[147,  96,  44],
        [147,  96,  44],
        [147,  96,  44],
        ...,
        [ 54,  65,  73],
        [ 55,  64,  73],
        [ 55,  64,  73]],

       [[147,  96,  44],
        [147,  96,  44],
        [147,  96,  44],
        ...,
        [ 54,  65,  73],
        [ 55,  64,  73],
        [ 55,  64,  73]],

       ...,

       [[165, 160, 169],
        [172, 167, 176],
        [181, 176, 185],
        ...,
        [200, 192, 199],
        [200, 192, 199],
        [200, 192, 199]],

       [[167, 162, 171],
        [175, 170, 179],
        [183, 178, 187],
        ...,
        [201, 193, 200],
        [201, 193, 200],
        [201, 193, 200]],

       [[168, 163, 172],
        [176, 171, 180],
        [184, 179, 188],
        ...,
        [202, 194, 201],
        [202, 194, 201],
        [202, 194, 201]]

In [19]:
cv2.imshow("image" , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
import numpy as np

In [22]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
img = cv2.imread("cat.jpg")
img = np.zeros([720,1280,3],np.uint8)
cv2.line(img,(0,0),(300,300),(147,96,44),10)
img = cv2.putText(img,"OPEN-CV",(300,500),font,4,(0,255,255),10)
img = cv2.circle(img,(500,630),105,(0,255,0),-1)

In [24]:
cv2.imshow("image" , img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.videoCapture()
ss = cv2.videoWriter()
ss.resize()